service: aws-bedrock

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-west-2

functions:
  generate_code_for_prompt:
    handler: bedrock_codes/code_generation.generate_code_for_prompt
    timeout: 600
    role: bedrockRole
    events:
      - httpApi: 'POST /bedrock/generate_code'

resources:
  Resources:
    bedrockRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /my/cust/path/
        RoleName: bedrock_role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: bedrock_policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:TagResource
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - bedrock:*
                    - s3:*
                  Resource: "*"